<a href="https://colab.research.google.com/github/AI4GoodE1/AI4GoodE1/blob/main/Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import io

In [2]:
# Get data
df = pd.read_csv('https://raw.githubusercontent.com/AI4GoodE1/AI4GoodE1/main/fraud_email_preprocessed.csv')
df

                                                    Text  Class
0      supply quality china s exclusive dimensions at...      1
1                            over  sidlet me know  thx        0
2      dear friend greetings to you i wish to accost ...      1
3      mr  cheung puihang seng bank ltd des voeux rd ...      1
4             not a surprising assessment from embassy        0
...                                                  ...    ...
10244  i called and was transferred to room but got n...      0
10245  travel well  i ll look forward to hearing your...      0
10246  follow up flag  follow upflag status  flaggedm...      0
10247  sbwhoeop bnumbersaturday january number number...      0
10248  fyi  we are revising call sheet for call to ka...      0

[10249 rows x 2 columns]